// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Data;

#nullable disable

namespace Repository.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240414183636_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Models.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            Color = "orange",
                            CreatedDate = new DateTime(2024, 4, 14, 22, 36, 36, 515, DateTimeKind.Local).AddTicks(1180),
                            Name = "Back End"
                        },
                        new
                        {
                            Id = 1001,
                            Color = "green",
                            CreatedDate = new DateTime(2024, 4, 14, 22, 36, 36, 515, DateTimeKind.Local).AddTicks(1210),
                            Name = "Front End"
                        },
                        new
                        {
                            Id = 1002,
                            Color = "black",
                            CreatedDate = new DateTime(2024, 4, 14, 22, 36, 36, 515, DateTimeKind.Local).AddTicks(1220),
                            Name = "Cyber Security"
                        });
                });

            modelBuilder.Entity("Domain.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EducationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EducationId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 30,
                            Capacity = 20,
                            CreatedDate = new DateTime(2024, 4, 14, 22, 36, 36, 515, DateTimeKind.Local).AddTicks(1270),
                            EducationId = 1000,
                            Name = "Group100"
                        },
                        new
                        {
                            Id = 32,
                            Capacity = 15,
                            CreatedDate = new DateTime(2024, 4, 14, 22, 36, 36, 515, DateTimeKind.Local).AddTicks(1280),
                            EducationId = 1001,
                            Name = "Group105"
                        },
                        new
                        {
                            Id = 33,
                            Capacity = 20,
                            CreatedDate = new DateTime(2024, 4, 14, 22, 36, 36, 515, DateTimeKind.Local).AddTicks(1280),
                            EducationId = 1002,
                            Name = "Group106"
                        },
                        new
                        {
                            Id = 34,
                            Capacity = 18,
                            CreatedDate = new DateTime(2024, 4, 14, 22, 36, 36, 515, DateTimeKind.Local).AddTicks(1280),
                            EducationId = 1002,
                            Name = "Group107"
                        });
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Models.Group", b =>
                {
                    b.HasOne("Domain.Models.Education", "Education")
                        .WithMany("Groups")
                        .HasForeignKey("EducationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Education");
                });

            modelBuilder.Entity("Domain.Models.Education", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
